services:
  frontend:
    image: tcgapptodreambornfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    restart: unless-stopped
